### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by jhimes144** [net-core-audio/portmidi#4]
Hello,

Thank you all for this amazing, simple to the point cross-platform midi library. It really saved me days of work.

Looking over the code, I can ascertain this library should only be worked in a single thread, or with careful locking. I suggest the readme be updated with a warning that this library is not thread-safe. It would also be great if thread-safety could be implemented!

EDIT: After working a bit further, it seems like running everything in a single thread is probably the best design anyways.

**Comment by peacecwz** [comment]
Hi @jhimes144 

Thanks for your reviews. Actually It was experimental implementation. After the implementation, I was thinking this topic. I'll add it to list but I haven't time to work on it. If I have free time I'll do

Thanks a lot your feedback
